include: package:lints/recommended.yaml

analyzer:
  exclude: ["**/gen/**", "examples"]
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    - cancel_subscriptions
    - directives_ordering
